trigger:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - 'docs/*'

pool:
  vmImage: 'ubuntu-16.04'
  demands:
    - npm

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '3.1.100'

steps:
- template: templates/build.yml
  parameters:
    buildConfiguration: $(buildConfiguration)
    wwwrootDir: $(wwwrootDir)
    dotnetSdkVersion: $(dotnetSdkVersion)